# Site settings
title: Datawake
baseurl: "/Datawake"
safe: true
lsi: false
highlighter: pygments
email: memex@soteradefense.com
website: http://www.soteradefense.com
description: > # this means to ignore newlines until "baseurl:"
    "Catching all of your information in our wake"

url: "http://sotera.github.io"
github_username:  Sotera
repository_url: https://github.com/Sotera/DatawakeDepot

show_downloads: true
zip_url: https://github.com/Sotera/Datawake/zipball/master
tar_url: https://github.com/Sotera/Datawake/tarball/master

markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
